#Author: Frosty_Flower

#Support both MiniMessage and ampersand formatting.
#PlaceholderAPI support.
#Default placeholders {player}, {message}, {prefix}, {suffix}, {world}.
#This is the default format for all groups.
chat-format: "<blue><hover:show_text:'{player}'>{player}:</hover></blue> &a{message}"

#World options.
#Only players in the same world as sender can see the message.
per-world: false