#Author: Frosty_Flower

#Support both MiniMessage and ampersand formatting.
#PlaceholderAPI support.
#Default placeholders {player}, {message}, {prefix}, {suffix} and {world}.
#This is the default format for all groups.
chat-format: "<hover:show_text:'{prefix}'><gray>[</gray>{prefix}<gray>]</gray></hover><gray> {player}:</gray> {message}"

#Group chat colours.
#Do not delete default group.
#Add more as you wish.
group-colours:
  admin: "&#57ffab"
  mvp: "&6"
  vip: "&c"
  default: "&r"

#Group chat formats. [Not implemented yet]
#Same placeholder as in default format.
#group-formats:
#  admin: "&7[&cAdmin&7] {player}: {message}"

#BETA FEATURE.
#World options.
#Only players in the same world as sender can see the message.
per-world: false

#Chat options.
#Allow player to use text inside angled bracket "<Example>" and it will parse as a copyable text.
chat-clipboard: true