name: ChatEnhancer
version: ${project.version}
main: net.frosty.chatEnhancer.ChatEnhancer
api-version: '1.18'
authors: [ Frosty_Flower, DanTheWman ]
description: A simple plugin use for customising chat.
softdepend:
  - Vault
  - PlaceholderAPI
permissions:
  chatenhancer.chatcolour:
    description: "Allow player to chat using colour code."
    default: op
  chatenhancer.bypassfilter:
    description: "Allow player to bypass the profanity filter in chat."
    default: op
  chatenhancer.admin:
    description: "Staff permission node."
    default: op
commands:
  chat-enhancer:
    aliases:
      - ce
    description: "Admin commands for chat enhancer."
    usage: "§cError: §4Invalid usage."
    permission: "chatenhancer.admin"
    permission-message: "§cError: §4You don't have the right to use this command."
    default: op